### PR TITLE
Add GNOME 45 Support

### PR DESCRIPTION
**Pull request by TheBrokenRail**
[The Porting Guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm)

### CODE REVIEW

**Review by Vishram1123 — APPROVED** [review]

**Comment by TheBrokenRail** [comment]
@lxylxy123456, any updates?

**Comment by lxylxy123456** [comment]
@TheBrokenRail Thanks for the PR. Have you tested the code? Which Linux distro are you using? Unfortunately Fedora 39 has not been released yet, so I cannot get access to gnome-shell 45 easily. Are you ok if we wait until Fedora 39 is released?

**Comment by TheBrokenRail** [comment]
I'm using Ubuntu 23.10 (which has GNOME 45). I'm using the extension myself since the keyboard popping up every 5 seconds is beyond annoying.

I'm fine waiting, especially since I have my modified version installed locally.

**Comment by lxylxy123456** [comment]
Submitted to gnome extensions website, currently under review: <https://extensions.gnome.org/review/47761>

**Pull request merged**
